### ISSUE TITLE
Maclary Todo List

### ISSUE THREAD

**Issue by k0d13** [maclary/maclary#3]
This is where I will keep features I plan to add and bugs I plan to fix.

- Async `fetchPrefix` on client object, to add support for custom prefixes
- ~~`HasPermissions(<bitfield>)` precondition, function that takes a bitfield as its first parameter, then returns a precondition class~~
- `CommandBuilder`, to make it easier to format command options
- Export more of the classes (like `Base`)
- ~~Remove the need for module 'twemoji-parser'~~
- Use lodash to format the list of missing permissions in preconditions
- ~~Replace 'zod' with a better library~~
- Add union preconditions, something like `Precondition.Either(Precondition.GuildOnly, Precondition.OwnerOnly)`
- Add ability to load single files in event and command managers.
- Add support i18n, maybe a plugin.
- Rework the development + guild id system.

**Comment by apteryxxyz** [comment]
Utilities: @maclary/context
